# Generated by Django 2.2.6 on 2019-11-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(default=None, max_length=255, null=True, verbose_name='Название сессии')),
                ('api_id', models.PositiveIntegerField(default=None, null=True, verbose_name='API ID')),
                ('api_hash', models.CharField(default=None, max_length=255, null=True, verbose_name='API Hash')),
                ('bot_token', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Токен бота (если это бот)')),
                ('is_bot', models.BooleanField(blank=True, default=None, null=True, verbose_name='Это бот')),
                ('is_active', models.BooleanField(blank=True, default=None, null=True, verbose_name='Активен (включен)')),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Configs',
            },
        ),
    ]
