# Generated by Django 2.2.8 on 2019-12-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialoguelistener',
            options={'verbose_name': 'dialogue listener', 'verbose_name_plural': 'dialogues listeners'},
        ),
    ]
