# Generated by Django 2.2.6 on 2019-11-21 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='ID отправителя')),
                ('tg_username', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Телеграм юзер')),
                ('tg_first_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя')),
                ('tg_last_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Фамилия')),
                ('tg_recently_status', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Последнее посещение')),
                ('is_bot', models.BooleanField(blank=True, default=None, null=True, verbose_name='Это бот')),
                ('is_contact', models.BooleanField(blank=True, default=None, null=True, verbose_name='Юзер из контактов')),
                ('is_scam', models.BooleanField(blank=True, default=None, null=True, verbose_name='Скомпроментирован')),
                ('is_support', models.BooleanField(blank=True, default=None, null=True, verbose_name='Это тех. поддержка')),
            ],
            options={
                'verbose_name': 'телеграм юзер',
                'verbose_name_plural': 'телеграм юзеры',
            },
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'config', 'verbose_name_plural': 'configs'},
        ),
        migrations.AlterField(
            model_name='config',
            name='is_active',
            field=models.BooleanField(blank=True, default=None, help_text='Изменять вручную не нужно.', null=True, verbose_name='Активен (включен)'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='ID сообщения')),
                ('text', models.TextField(blank=True, default=None, null=True, verbose_name='Текст сообщения')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('sender', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram.TelegramUser', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]
