# Generated by Django 2.2.6 on 2019-11-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_auto_20191121_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='ID чата')),
                ('tg_chat_type', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Тип чата, напр. супергруппа')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чаты',
            },
        ),
    ]
