# Generated by Django 2.2.6 on 2019-11-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='tg_chat_username',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Username чата'),
        ),
    ]
