# Generated by Django 2.2.6 on 2019-11-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0007_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='ID чата'),
        ),
        migrations.AddField(
            model_name='message',
            name='chat_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Title чата'),
        ),
        migrations.AddField(
            model_name='message',
            name='chat_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Тип чата, напр. супергруппа'),
        ),
        migrations.AddField(
            model_name='message',
            name='chat_username',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Username чата'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_first_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='ID отправителя'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_is_bot',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Это бот'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_is_contact',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Юзер из контактов'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_is_scam',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Скомпроментирован'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_is_support',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Это тех. поддержка'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_last_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_recently_status',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Последнее посещение'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_username',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, verbose_name='Телеграм юзер'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='tg_username',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, verbose_name='Телеграм юзер'),
        ),
    ]
