# Generated by Django 2.2.6 on 2019-11-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_auto_20191121_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='access_token',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Токен доступа к API'),
        ),
    ]
