# Generated by Django 2.2.6 on 2019-11-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0009_config_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='is_ready',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Готов к использованию'),
        ),
    ]
