# Generated by Django 2.2.6 on 2019-11-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0010_config_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(blank=True, choices=[('Incoming', 'Входящее'), ('Sent', 'Отправленное')], default=None, max_length=255, null=True, verbose_name='Тип сообщения'),
        ),
    ]
