# Generated by Django 2.2.6 on 2019-11-25 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0011_message_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Middleware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middleware_type', models.CharField(choices=[('trigger_middleware', 'Trigger Middleware')], default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'middleware',
                'verbose_name_plural': 'trigger middleware',
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(blank=True, choices=[('Incoming', 'Входящее'), ('Sent', 'Исходящее')], default=None, max_length=255, null=True, verbose_name='Тип сообщения'),
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('middleware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telegram.Middleware')),
                ('words', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Триггерные слова')),
                ('is_enabled', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активно')),
                ('app', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram.Config', verbose_name='Приложение')),
            ],
            options={
                'verbose_name': 'триггер',
                'verbose_name_plural': 'триггеры',
            },
            bases=('telegram.middleware',),
        ),
    ]
