# Generated by Django 2.2.6 on 2019-11-25 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0012_auto_20191125_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='app',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram.Config', verbose_name='Приложение'),
        ),
        migrations.AlterField(
            model_name='middleware',
            name='middleware_type',
            field=models.CharField(choices=[('trigger_middleware', 'Trigger Middleware')], default=None, help_text='Не доступно для ручного изменения.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='words',
            field=models.CharField(blank=True, default=None, help_text='Через запятую', max_length=500, null=True, verbose_name='Триггерные слова'),
        ),
    ]
