# Generated by Django 2.2.6 on 2019-11-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0014_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reason',
            options={'verbose_name': 'обработчик', 'verbose_name_plural': 'обработчики'},
        ),
        migrations.AddField(
            model_name='reason',
            name='type',
            field=models.CharField(choices=[('apps.common.secret_note.reasons', 'Reason'), ('apps.common.other_app.reasons', 'Reason'), ('apps.common.second_one_app.reasons', 'Reason')], default=None, max_length=500, null=True, verbose_name='Обработчик'),
        ),
    ]
