# Generated by Django 2.2.6 on 2019-11-26 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0016_auto_20191126_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='reason',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram.TriggerReason', verbose_name='Обработчик триггеров'),
        ),
    ]
